### ISSUE TITLE
[destructive_clip] broken

### ISSUE THREAD

**Issue by vmario89** [eridur-de/mightyscape-1.2#148]
```
/home/himbeere/.local/lib/python3.12/site-packages/systemd.py:16: DeprecationWarning: This package has been renamed to cysystemd, please use this instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/himbeere/.config/inkscape/extensions/mightyscape-1.2/extensions/fablabchemnitz/destructive_clip/destructive_clip.py", line 219, in <module>
    DestructiveClip().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 250, in run
    self.save_raw(self.effect())
                  ^^^^^^^^^^^^^
  File "/home/himbeere/.config/inkscape/extensions/mightyscape-1.2/extensions/fablabchemnitz/destructive_clip/destructive_clip.py", line 205, in effect
    path = str(inkex.Path(self.linesgmentsToSimplePath(clippedSegments)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/inkscape/extensions/inkex/paths.py", line 1355, in __init__
    self.append(PathCommand.letter_to_class(item[0])(*item[1]))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Move.__init__() takes 3 positional arguments but 7 were given

```
sample file: ![sample](https://github.com/eridur-de/mightyscape-1.2/assets/5631071/c9fb5e21-1aed-4017-a260-f21276302f0a)

**Comment by vmario89** [comment]
fixed by https://github.com/eridur-de/mightyscape-1.2/commit/5cc30dfc73a18803d705db27b1477dd42256f8fe
